version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fitlens_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER:     fitlens
      POSTGRES_PASSWORD: fitlens_secret
      POSTGRES_DB:       fitlens_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7-alpine
    container_name: fitlens_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  adminer:
    image: adminer:latest
    container_name: fitlens_adminer
    restart: unless-stopped
    ports:
      - '8080:8080'

volumes:
  postgres_data:
  redis_data:
